### ISSUE TITLE
Open Data Sources

### ISSUE THREAD

**Issue by jlev** [Netzfreiheit/Contact-Your-MEP#23]
Hi, I'm interested in building more MEP contact tools, and would love to build on the json and csv data you have here. Do you have the scripts you used to generate those files, so that I can ensure they are still accurate and up to date?

**Comment by burnoutberni** [comment]
You can find loads of information about the EP, its members and its committees and proceedings on http://parltrack.euwiki.org/ under a free license and in JSON.
